// <auto-generated />
using System;
using CisEng.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CisEng.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190921192540_applaytraining")]
    partial class applaytraining
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CisEng.Models.AppliesforTraining", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("studentApplay");

                    b.Property<string>("studentPublishtraining");

                    b.Property<string>("trainingid");

                    b.HasKey("id");

                    b.ToTable("AppliesforTraining");
                });

            modelBuilder.Entity("CisEng.Models.CisStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentEmail");

                    b.Property<string>("StudentImage");

                    b.Property<string>("StudentLevel");

                    b.Property<string>("StudentName");

                    b.Property<string>("password");

                    b.HasKey("Id");

                    b.ToTable("CisStudent");
                });

            modelBuilder.Entity("CisEng.Models.Comments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PostId");

                    b.Property<string>("StudentId");

                    b.Property<DateTime>("Time");

                    b.Property<string>("comment");

                    b.HasKey("id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CisEng.Models.Followus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("accept");

                    b.Property<string>("recever");

                    b.Property<string>("sender");

                    b.HasKey("id");

                    b.ToTable("Followus");
                });

            modelBuilder.Entity("CisEng.Models.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CisStudentId");

                    b.Property<string>("PostPrivte");

                    b.Property<string>("Postcontaint");

                    b.Property<string>("Technology");

                    b.Property<string>("Title");

                    b.Property<DateTime>("dateTime");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CisEng.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addition");

                    b.Property<string>("Age");

                    b.Property<string>("Appreciation");

                    b.Property<string>("Carear");

                    b.Property<string>("Colleage");

                    b.Property<string>("Company_youWork");

                    b.Property<string>("Experience");

                    b.Property<string>("Language");

                    b.Property<string>("Program_Language");

                    b.Property<string>("StudentId");

                    b.Property<string>("University");

                    b.Property<string>("country");

                    b.Property<string>("kind");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("CisEng.Models.ResponsetoComment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Containt");

                    b.Property<string>("idof");

                    b.Property<string>("idofcomment");

                    b.Property<string>("idofstudent");

                    b.Property<string>("time");

                    b.HasKey("id");

                    b.ToTable("ResponsetoComment");
                });

            modelBuilder.Entity("CisEng.Models.Taining", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Containt");

                    b.Property<string>("place");

                    b.Property<string>("sponser");

                    b.Property<string>("technology");

                    b.Property<string>("time");

                    b.HasKey("id");

                    b.ToTable("Taining");
                });

            modelBuilder.Entity("CisEng.Models.responsetorespone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Containt");

                    b.Property<string>("idofresponse");

                    b.Property<string>("idofstudent");

                    b.Property<string>("time");

                    b.HasKey("id");

                    b.ToTable("responsetorespone");
                });
#pragma warning restore 612, 618
        }
    }
}
