// <auto-generated />
using CisEng.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CisEng.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190819114944_updateposts")]
    partial class updateposts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CisEng.Models.CisStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentEmail");

                    b.Property<string>("StudentImage");

                    b.Property<string>("StudentLevel");

                    b.Property<string>("StudentName");

                    b.Property<string>("password");

                    b.HasKey("Id");

                    b.ToTable("CisStudent");
                });

            modelBuilder.Entity("CisEng.Models.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CisStudentId");

                    b.Property<string>("File");

                    b.Property<string>("Image");

                    b.Property<bool>("PostPrivte");

                    b.Property<string>("Postcontaint");

                    b.Property<string>("Technology");

                    b.Property<int>("Title");

                    b.Property<string>("Video");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CisEng.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addition");

                    b.Property<string>("Age");

                    b.Property<string>("Appreciation");

                    b.Property<string>("Carear");

                    b.Property<string>("Colleage");

                    b.Property<string>("Company_youWork");

                    b.Property<string>("Experience");

                    b.Property<string>("Language");

                    b.Property<string>("Program_Language");

                    b.Property<string>("StudentId");

                    b.Property<string>("University");

                    b.Property<string>("country");

                    b.Property<string>("kind");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
